# The Famous Machine Learning Libraries In Python


## 1- Introduction to Numpy

>**NumPY** is a package that provides support for multi-dimensional arrays and matrices, along with mathematical functions to operate on them. 
 **NumPy** is short for Numerical Python,it's an open source library for Scientific Computing in python. It provides support for multi-dimensional arrays and matrices, along with efficient mathematical functions for operating on these arrays

### 1.1 Tables

In [22]:
# Let's bring in numpy
import numpy as np

#### A-Using a liste

In [16]:
#create a liste
my_list=[1,2,3,4,5,6,7]

#  create the table
vect=np.array(my_list)
vect


array([1, 2, 3, 4, 5, 6, 7])

In [4]:
type(vect)

numpy.ndarray

In [6]:
vect.dtype

dtype('int32')

In [5]:
vect.ndim

1

In [3]:
len(vect)

7

In [7]:
vect.shape

(7,)

In [8]:
vect.size

7

In [11]:
#  We access a specific location in the table by referring to its row and column inside square braces.
vect[0,]

1

In [12]:
vect[5,]

6

In [13]:
#  we are asking Python to give us everything up to the number 4 in our array.
vect[:4]

array([1, 2, 3, 4])

In [15]:
vect[:2]

array([1, 2])

In [17]:
vect.max()

7

In [18]:
vect.min()

1

In [19]:
vect.argmax()

6

In [20]:
vect.argmin()

0

#### B- Using Python Fonctions :
in this section we present other way to create tables in python using some function ,the previous operation are always available , so we don't need to repete then again 

In [24]:
#create a tables that contain 10 elements in the interval [0,9] with step=1
vect_1=np.arange(0,10)
vect_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
#create a tables that contain 5 elements in the interval [0,9] with step=2

vect_2=np.arange(0,10,2)
vect_2

array([0, 2, 4, 6, 8])

In [27]:
#create a tables 5*1 with value=0
vect_3=np.zeros(5)
vect_3

array([0., 0., 0., 0., 0.])

In [29]:
#create a tables 5*1 with value=1
vect_4=np.ones(5)
vect_4

array([1., 1., 1., 1., 1.])

In [102]:
#create a tables 10*1 in the interval [0,50]

vect_5=np.linspace(0,50,10)
vect_5

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [32]:
#create a tables 5*1 in the interval [2,4]

vect_6=np.linspace(2,4,5)
vect_6

array([2. , 2.5, 3. , 3.5, 4. ])

#### C- Using random Fonctions :


In [35]:
from numpy import random 

In [37]:
#create a tables with only 2 elements choosed randomly in the interval [0,1]
vect_7=random.rand(2)
vect_7

array([0.1092818 , 0.88300291])

In [59]:
#create a tables with only 3 elements choosed randomly in the interval [-1,1]

vect_8=random.randn(3)
vect_8

array([ 0.93484684, -0.32883687, -0.94945835])

### 1.2 Matrix

#### A-Using a liste

In [105]:
#create a liste
my_list= [[1,2,3],[4,5,6],[7,9,10],[11,15,8]]
#create a matrix
mat=np.array(my_list)
mat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  9, 10],
       [11, 15,  8]])

In [64]:
type(mat)

numpy.ndarray

In [65]:
mat.dtype

dtype('int32')

In [66]:
mat.ndim

2

In [69]:
len(mat)

4

In [70]:
mat.shape

(4, 3)

In [106]:
#we are searching the total number of elements
mat.size

12

In [73]:
mat[0,2]

3

In [74]:
mat[3,2]

8

In [76]:
mat[:,2]

array([ 3,  6, 10,  8])

In [77]:
mat[1,:]

array([4, 5, 6])

In [78]:
mat[:,:]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  9, 10],
       [11, 15,  8]])

In [79]:
mat.max()

15

In [80]:
mat.min()

1

In [81]:

mat.argmin()

0

In [82]:
mat.argmax()

10

#### B- Using Python Fonctions :
in this section we present other way to create a matrix in python using some functions,the previous operations are always available , so we don't need to repete then again.


In [94]:
#create two matrix 5*10, the values of the first matrix are in the interval [0,4], the second are in [0,9]
mat_1,mat_2=np.mgrid[0:5,0:10]
mat_1


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])

In [85]:
mat_2

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [96]:
#create a matrix 3*5 with value=1

mat_3=np.ones((3,5))
mat_3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [98]:
#create a matrix 4*3 with value=0

mat_4=np.zeros((4,3))
mat_4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [99]:
#create a matrix 4*4 with diagonal =1 and 0 for the rest
mat_5=np.eye(4)
mat_5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### C- Using random Fonctions :


In [103]:
#create a matrix 5*3,that elements choosed randomly in the interval [0,1)

mat_6=random.rand(5,3)
mat_6

array([[0.58463575, 0.60000211, 0.07813   , 0.74460997, 0.79453364],
       [0.62754903, 0.83146392, 0.09306854, 0.60445243, 0.66885455],
       [0.17659178, 0.27718082, 0.12840743, 0.97587213, 0.41818258],
       [0.79272673, 0.13390008, 0.29502097, 0.09887599, 0.01605921],
       [0.48042266, 0.60419603, 0.86922604, 0.29749683, 0.7023666 ]])

In [104]:
#create a matrix 4*4,that elements choosed randomly in the interval [-1,1)

mat_7=random.randn(4,4)
mat_7

array([[ 0.45866261,  0.90222358, -0.09209165,  1.41929138],
       [-0.38968349, -1.84201861, -0.61157922,  1.45185775],
       [ 0.58525607,  1.47264697,  0.03624602, -0.05103574],
       [-0.91691082, -0.69671058, -1.46954841, -2.48486358]])